# Generated by Django 4.2.5 on 2023-09-22 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150, verbose_name='descricao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.IntegerField(verbose_name='telefone')),
                ('numero_sus', models.IntegerField( verbose_name='numero_sus')),
                ('descricao', models.CharField(max_length=150, verbose_name='descricao')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.hospital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de telefone')),
                ('nome', models.CharField(max_length=50, verbose_name=' nome')),
                ('cpf', models.IntegerField(verbose_name=' cpf: ')),
                ('detalhes', models.CharField(max_length=150)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.hospital')),
            ],
        ),
    ]
