# Generated by Django 4.2.5 on 2023-09-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_sus',
            field=models.IntegerField(verbose_name='numero_sus'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.IntegerField(verbose_name='telefone'),
        ),
    ]
