# Generated by Django 4.2.5 on 2023-09-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_paciente_numero_sus_alter_paciente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='descricao',
            field=models.CharField(max_length=150, verbose_name='descricao'),
        ),
    ]
