# Generated by Django 4.2.5 on 2023-09-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_paciente_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name=' cpf: '),
        ),
    ]
