# Generated by Django 4.2.6 on 2023-10-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_medico_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data', models.IntegerField(verbose_name='data')),
                ('orario', models.IntegerField(verbose_name='orario')),
                ('Medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medico')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.hospital')),
            ],
        ),
    ]
