# Generated by Django 4.2.7 on 2023-11-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_cronograma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronograma',
            old_name='Medico',
            new_name='medico',
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='data',
            field=models.CharField(max_length=10, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='orario',
            field=models.CharField(max_length=15, verbose_name='orario'),
        ),
    ]
