# Generated by Django 4.2.7 on 2023-11-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_medico_cronograma_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10, verbose_name='data')),
                ('horario', models.CharField(max_length=15, verbose_name='horario')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.hospital')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente')),
            ],
        ),
    ]
