# Generated by Django 4.2.7 on 2023-11-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_cronograma_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doença_cronica',
            field=models.CharField(default=1, max_length=150, verbose_name='doença_cronica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='sintomas',
            field=models.CharField(default=1, max_length=150, verbose_name='descricao'),
            preserve_default=False,
        ),
    ]
