# Generated by Django 4.2.7 on 2023-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_paciente_doença_cronica_paciente_sintomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(default=1, verbose_name='idade'),
            preserve_default=False,
        ),
    ]
