# Generated by Django 5.0 on 2023-12-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_paciente_doença_cronica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmada', 'Confirmada')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
