# Generated by Django 4.2.7 on 2023-12-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_alter_consulta_status_alter_medico_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(max_length=20, verbose_name='status'),
        ),
    ]
