# Generated by Django 4.2.7 on 2023-12-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_alter_consulta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='status'),
        ),
    ]
