# Generated by Django 5.1.2 on 2024-10-14 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario_cadastrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_cadastrados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
