# Generated by Django 5.1.2 on 2024-10-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_remove_consulta_horario_paciente_cpf_triagem_glicose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='data',
            field=models.DateField(max_length=10, verbose_name='data'),
        ),
    ]
