# Generated by Django 5.1.2 on 2024-10-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_alter_cronograma_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='data',
            field=models.DateTimeField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='horario',
            field=models.TimeField(default='09:00:00', verbose_name='horario'),
        ),
    ]
