# Generated by Django 5.1.2 on 2024-10-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_prontuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.PROTECT, to='cadastros.paciente'),
            preserve_default=False,
        ),
    ]
