# Generated by Django 5.1.2 on 2024-10-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_comentario_usuario_alter_cronograma_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='medico',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.PROTECT, to='cadastros.medico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='horario',
            field=models.CharField(max_length=15, verbose_name='orario'),
        ),
    ]
