# Generated by Django 5.1.2 on 2024-10-31 11:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_remove_comentario_usuario_prontuario_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prontuario',
            new_name='Atendimento',
        ),
    ]
