# Generated by Django 5.1.2 on 2024-10-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_rename_prontuario_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='horario',
            field=models.CharField(max_length=15, verbose_name='Horario'),
        ),
    ]
