# Generated by Django 5.1.2 on 2024-11-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_cronograma_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronograma',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='horario',
            field=models.CharField(max_length=15, verbose_name='horario'),
        ),
    ]
