# Generated by Django 5.1.3 on 2024-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_remove_cronograma_paciente_alter_cronograma_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultas_agendadas', models.IntegerField(default=0)),
                ('atendimentos_realizados', models.IntegerField(default=0)),
                ('pacientes_espera', models.IntegerField(default=0)),
                ('notificacoes_pendentes', models.IntegerField(default=0)),
            ],
        ),
    ]
