# Generated by Django 5.1.3 on 2024-11-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_estatisticas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='status',
            field=models.CharField(default='lida', max_length=255),
            preserve_default=False,
        ),
    ]
