# Generated by Django 4.2.5 on 2023-09-22 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
